#!/usr/bin/env bash
set -euo pipefail

export UNIRUST_SCALE_COUNT="${UNIRUST_SCALE_COUNT:-1000000}"
export UNIRUST_SCALE_BATCH="${UNIRUST_SCALE_BATCH:-100000}"
export UNIRUST_SCALE_OVERLAP="${UNIRUST_SCALE_OVERLAP:-0.01}"
export UNIRUST_SCALE_DATA_DIR="${UNIRUST_SCALE_DATA_DIR:-./scale_data}"

# 32GB RAM shard tuning defaults; adjust per host if needed.
export UNIRUST_BLOCK_CACHE_MB="${UNIRUST_BLOCK_CACHE_MB:-12288}"
export UNIRUST_WRITE_BUFFER_MB="${UNIRUST_WRITE_BUFFER_MB:-1024}"
export UNIRUST_MAX_WRITE_BUFFERS="${UNIRUST_MAX_WRITE_BUFFERS:-6}"
export UNIRUST_TARGET_FILE_MB="${UNIRUST_TARGET_FILE_MB:-256}"
export UNIRUST_LEVEL_BASE_MB="${UNIRUST_LEVEL_BASE_MB:-2048}"
export UNIRUST_BLOOM_BITS_PER_KEY="${UNIRUST_BLOOM_BITS_PER_KEY:-10}"
export UNIRUST_MEMTABLE_PREFIX_BLOOM_RATIO="${UNIRUST_MEMTABLE_PREFIX_BLOOM_RATIO:-0.1}"

exec cargo run --release --bin scale_persistent
